apiVersion: v1
kind: Service
metadata:
  namespace: simple
  name: micro-svc-preview
  labels:
    app: micro
    strategy: blue-green
    role: preview
  annotations:
    # This service points to the PREVIEW (new) version
    description: "Preview traffic service - for testing new version before promotion"
spec:
  type: LoadBalancer
  selector:
    app: micro
    # Note: Argo Rollouts automatically manages the selector to point to preview pods
  ports:
    - port: 9876
      targetPort: 9876
      protocol: TCP
      name: http
  sessionAffinity: None
