apiVersion: v1
kind: Service
metadata:
  name: micro-svc
  labels:
    app: micro
    strategy: rolling-update
spec:
  type: LoadBalancer
  selector:
    app: micro
  ports:
  - port: 9876
    targetPort: 9876
    protocol: TCP
    name: http
  # Session affinity can be useful for stateful apps
  # For this demo app, it's not required but shown for completeness
  sessionAffinity: None
